site_name: SparkFun Qwiic OLED Arduino Library - Examples

nav:
  - Example 1 - Hello: "ex_01_hello.md"
  - Example 2 - Shapes: "ex_02_lines.md"
  - Example 3 - Bitmaps: "ex_03_bitmaps.md"
  - Example 4 - Text: "ex_04_text.md"
  - Other Examples: "ex_other.md"              